// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnLQGXVhLADmLrjtT26PPjtuLvsNSd9U',
    appId: '1:989230290242:web:7c91b9f56f8fa923ea64db',
    messagingSenderId: '989230290242',
    projectId: 'recruitment-c45b3',
    authDomain: 'recruitment-c45b3.firebaseapp.com',
    storageBucket: 'recruitment-c45b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNEVEO_YwiObgglIWv1DdxqnX7LGoAYs',
    appId: '1:989230290242:android:73d86f7d64ff56f5ea64db',
    messagingSenderId: '989230290242',
    projectId: 'recruitment-c45b3',
    storageBucket: 'recruitment-c45b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8gi2VY0oR-YHboAIa5adMru_i72wxsH8',
    appId: '1:989230290242:ios:7a26b4f36a7aabdeea64db',
    messagingSenderId: '989230290242',
    projectId: 'recruitment-c45b3',
    storageBucket: 'recruitment-c45b3.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8gi2VY0oR-YHboAIa5adMru_i72wxsH8',
    appId: '1:989230290242:ios:d18ae67e69d7d76eea64db',
    messagingSenderId: '989230290242',
    projectId: 'recruitment-c45b3',
    storageBucket: 'recruitment-c45b3.appspot.com',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
